# Generated by Django 4.2.11 on 2026-04-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_lineuser_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='วันที่')),
                ('description', models.CharField(max_length=200, verbose_name='เหตุผล/ชื่อวันหยุด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'วันหยุด',
                'verbose_name_plural': 'วันหยุด',
                'ordering': ['date'],
            },
        ),
        migrations.AlterField(
            model_name='room',
            name='booking_name',
            field=models.CharField(help_text='key ที่ใช้ใน URL เช่น netflix, mini, canva, chat-gpt, meeting_f1', max_length=50, unique=True),
        ),
    ]
