# Generated by Django 4.2.11 on 2026-04-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_holiday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notified_10min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='notified_15min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='notified_start',
            field=models.BooleanField(default=False),
        ),
    ]
