# Generated by Django 4.2.11 on 2026-04-21 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_notification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='eligible_users',
            field=models.TextField(blank=True, help_text='ผู้มีสิทธิ์ใช้บริการ เช่น นักศึกษา, บุคลากร'),
        ),
        migrations.AddField(
            model_name='room',
            name='facilities',
            field=models.TextField(blank=True, help_text='อุปกรณ์/สิ่งอำนวยความสะดวก (แต่ละรายการขึ้นบรรทัดใหม่)'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_booking_hours',
            field=models.IntegerField(default=2, help_text='เวลาจองสูงสุดต่อครั้ง (ชั่วโมง)'),
        ),
        migrations.AddField(
            model_name='room',
            name='min_attendees',
            field=models.IntegerField(default=1, help_text='จำนวนผู้ใช้ขั้นต่ำ'),
        ),
        migrations.AddField(
            model_name='room',
            name='rules',
            field=models.TextField(blank=True, help_text='กฎระเบียบการใช้ห้อง (แต่ละข้อขึ้นบรรทัดใหม่)'),
        ),
    ]
