# Generated by Django 4.2.11 on 2026-04-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_room_add_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='how_to_use',
            field=models.TextField(blank=True, help_text='ขั้นตอนการใช้บริการ (แต่ละขั้นตอนขึ้นบรรทัดใหม่)'),
        ),
    ]
