# Generated by Django 4.2.11 on 2026-04-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_roomdevice'),
        ('booking', '0006_room_add_how_to_use'),
    ]

    operations = [
    ]
