# Generated by Django 4.2.11 on 2026-04-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_roomclosure'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('imported_at', models.DateTimeField()),
                ('added_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
