# Generated by Django 5.0.4 on 2026-07-17 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_update_room_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdevice',
            name='group_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='กลุ่มอุปกรณ์ (ใช้เมื่อไม่สังกัดห้อง)'),
        ),
        migrations.AlterField(
            model_name='roomdevice',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='booking.room', verbose_name='ห้อง'),
        ),
    ]
