# Generated by Django 5.0.4 on 2026-08-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_roomdevice_group_name_alter_roomdevice_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allow_overlap',
            field=models.BooleanField(default=False, help_text='ยอมให้ผู้ใช้คนเดียวจองห้องนี้ทับเวลากับห้องอื่นได้ (สำหรับพื้นที่กลุ่ม/พื้นที่เปิด เช่น โต๊ะประชุม)'),
        ),
    ]
