# Generated by Django 5.0.4 on 2026-08-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_room_allow_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_online',
            field=models.BooleanField(default=False, help_text='บริการออนไลน์ที่ไม่ต้องเข้าอาคาร (เช่น เครื่องเสมือน Canva/Netflix) จองได้ทุกวันตามเวลาเปิด-ปิดของห้องนี้ ไม่ถูกจำกัดด้วยเวลาเปิดอาคารหรือวันหยุด'),
        ),
    ]
