# Generated by Django 5.0.4 on 2026-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_room_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='day_round_enabled',
            field=models.BooleanField(default=True, help_text='เปิดจองรอบกลางวัน (08:30–17:00) หรือไม่ — ปิดเมื่อทรัพยากรถูกใช้ที่จุดบริการอื่น ในเวลาราชการ เช่น บัญชี Netflix ที่ให้บริการอยู่ที่ Edutainment Zone ช่วงกลางวัน'),
        ),
    ]
