# Generated by Django 5.0.4 on 2026-08-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_room_day_round_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaydate',
            name='source',
            field=models.CharField(choices=[('manual', 'เจ้าหน้าที่เพิ่มเอง'), ('auto', 'ดึงจากปฏิทินวันหยุดอัตโนมัติ')], default='manual', max_length=10, verbose_name='ที่มา'),
        ),
    ]
